import type { GuideContent } from "./types";

/** The guide to the application, in English. It describes what is actually on the screens (docs/GUIDE.md). */
export const guideEn: GuideContent = {
  about:
    "Anvero gathers the orders from Allegro and Erli in one place and follows them from the moment they arrive to the parcel: you can see what to make, pack and send and what is late, buy labels, answer buyers, check the fees and the margin, and prepare the report for the accountant. It reads from Allegro and Erli, and what it changes itself it sends to them only once safe mode is switched off.",
  groups: {
    basics: "Basics",
    daily: "Daily work",
    money: "Money and accounts",
    setup: "Settings and administration",
  },
  sections: [
    {
      id: "start",
      group: "basics",
      title: "First steps: the menu and the basics",
      path: "/dashboard",
      image: "menu",
      intro:
        "After you sign in, the menu on the left holds every part of the application. The numbers beside the items say what is waiting for you, so often you do not need to open anything to know where to start.",
      parts: [
        { name: "The menu on the left", text: "Dashboard, Orders, To make, Assortment, Labels, Returns and claims, Inbox, Finance, Sales report, Settings and Help. The arrow at the top folds it down to icons. Under \"Orders\" a list of statuses and channels opens, with the number of orders in each." },
        { name: "The numbers beside the items", text: "How many orders wait to be sent (red when one is past its deadline), how many items are to be made, how many returns and claims need you, how many messages are unread. An orange dot beside Settings means something in the app status needs attention." },
        { name: "The \"Safe mode\" bar", text: "A green bar above the page: while it is there, Anvero sends nothing to Allegro or Erli and only records the changes. Status changes, tracking numbers and replies reach the marketplaces only once safe mode is switched off in Settings." },
        { name: "The foot of the menu", text: "The language switch (Polish and English), light and dark mode, and \"Log out\". The look of the application (Classic or Papier) is changed in Settings." },
      ],
      actions: [
        "Go to a part by clicking it in the menu or a tile on the Dashboard.",
        "Fold the menu to give the tables more room.",
        "Change the language and the theme without leaving the page.",
      ],
      tips: [
        "You see only the parts an administrator gave you access to (Settings → Users). A missing menu item usually means no permission, not an error.",
        "A new person has nothing to set up: the connections to Allegro and Erli, the import schedule and safe mode are the administrator's.",
      ],
    },
    {
      id: "dashboard",
      group: "daily",
      title: "Dashboard",
      path: "/dashboard",
      image: "dashboard",
      intro: "The start page: what is waiting, what is on fire and how sales are going, on one screen.",
      parts: [
        { name: "Waiting for you", text: "Tiles for the queues: To make, Unpaid, To ship and Past deadline, each with its number. A click opens the order list already filtered to that queue." },
        { name: "Needs attention", text: "Things not to miss: orders cancelled on the marketplace but still active here, problems in the app status, and unread buyer messages." },
        { name: "At a glance", text: "Orders this week, revenue and the number of orders in progress, and the split by sales channel (Allegro, Erli)." },
        { name: "Nearest dispatch deadlines", text: "The orders with the nearest dispatch date, with how long is left or how late they are." },
        { name: "Recent orders", text: "The newest orders with channel, buyer, status and amount; the number opens the order." },
      ],
      actions: [
        "Start the day with \"Past deadline\" and \"To ship\".",
        "Open an order from the recent or the deadlines list.",
        "Go to the app status when a warning appears.",
      ],
    },
    {
      id: "orders",
      group: "daily",
      title: "Orders",
      path: "/orders",
      image: "orders",
      intro: "The list of every order from Allegro and Erli. Here you find an order, filter them and work on many at once.",
      parts: [
        { name: "Work queues", text: "All, To make, Unpaid, To ship, Past deadline, Starred and Flagged. Beside them, a filter by status (New, In progress, Ready to ship, Shipped, Delivered, Cancelled) and by channel." },
        { name: "Search and filters", text: "Searches the order number, buyer, product or SKU, city, parcel locker and tracking number. \"Filters\" adds source, status and a date range. What you type is not left in the address or the browser's history." },
        { name: "The imports bar", text: "Shows when orders were last fetched from Allegro and from Erli and how many were new. The \"Import orders\" button fetches them at once; otherwise the application does it by itself every few minutes." },
        { name: "The table", text: "Anvero's number (AN-000123) and the marketplace's, items with a picture, buyer, status, shipping (carrier, number, tracking), amount and payment, marks (star, flag, note)." },
        { name: "Sorting", text: "Newest, Oldest, or \"At risk first\" (the least time to the deadline)." },
      ],
      actions: [
        "Open an order by clicking its row.",
        "Select several orders and set their status, or add a star or a flag, in one go.",
        "Mark an order with a star or a flag so it is easy to find later.",
        "Come back to the list with the filters kept after looking at an order (the \"previous\" and \"next\" arrows on the order page).",
      ],
      tips: [
        "An order cancelled on Allegro or Erli carries a warning until you deal with it here. Check it before packing.",
        "A deleted order is not lost: it can be restored from the order page.",
      ],
    },
    {
      id: "order",
      group: "daily",
      title: "The order page",
      path: "/orders",
      image: "order",
      intro: "Everything about one order: what was bought, by whom, where to, how it was paid, what is going on with the parcel and what has happened to it.",
      parts: [
        { name: "Header and next step", text: "The number, channel, status and the \"Mark as…\" button, which moves the order on by one stage. The arrows beside it go to the previous and next order of the list." },
        { name: "Items", text: "The products with quantity and price. The \"-\" and \"+\" buttons in the \"Packed\" column mark pieces as packed; the heading shows how many of how many are ready." },
        { name: "Shipping", text: "The order's parcels with tracking. Add a number on the \"Own number\" tab, buy a label in \"Allegro label\", or make a parcel locker shipment in \"InPost\"." },
        { name: "Internal note", text: "A field for your own note. It is only in Anvero: neither the buyer nor the marketplace sees it." },
        { name: "Folded rows under the note", text: "Status history (who changed it and when), Marketplace fees (the commissions and other fees for this order and what is left of it), The buyer's other orders, and Technical data." },
        { name: "The column on the right", text: "Buyer (details and the marketplace login), Delivery (the method, the pickup point or the recipient's address, a button to copy the address), Invoice (whether the buyer asked for one) and Payment (whether and when it was paid)." },
        { name: "Messages and returns", text: "When the buyer has written, or there is a return or claim, a card appears with the conversation, the reply box and the deadlines." },
      ],
      actions: [
        "Move the order on with the \"Mark as…\" button, or pick a status from the list.",
        "Change the status and add a tracking number; with safe mode off they reach Allegro and Erli.",
        "Buy a label or make an InPost shipment without leaving the order.",
        "Save your own note, which no one outside the team sees.",
        "Delete the order and restore it.",
      ],
      tips: [
        "The personal data in orders is anonymized by itself after the retention period. The order then stays (amounts, items) without the buyer's data. More in Help → GDPR.",
      ],
    },
    {
      id: "production",
      group: "daily",
      title: "To make",
      path: "/production",
      image: "production",
      intro: "The list for the workshop: what to make, and how many, for the paid orders still waiting, the most urgent first.",
      parts: [
        { name: "Groups", text: "The products grouped by the day their orders must go out: overdue, today, tomorrow, later days and no deadline. Each group shows how much is done." },
        { name: "A product's row", text: "The quantity to make, a picture (it grows when you point at it), the name and SKU, and the orders the product is for." },
        { name: "The bar at the top", text: "A status filter (All, New, In progress), \"Hide made\", a search (by order number, login, name or product; several phrases separated by commas), and a summary of the progress in pieces, products and orders." },
      ],
      actions: [
        "Tick products off as they are made; everyone using the database sees the tick.",
        "Hide what is made, to see only what is left.",
        "Print the list with the \"Print\" button.",
        "Go from a product to its order.",
      ],
    },
    {
      id: "catalog",
      group: "daily",
      title: "Assortment",
      path: "/catalog",
      image: "catalog",
      intro: "Every offer in the Allegro account, with its pictures, sales and margin, and how the same product stands on Erli. Read only: nothing here changes an offer on a marketplace.",
      parts: [
        { name: "The category tree", text: "Allegro's categories with the number of offers; a click shows the offers in that category and everything under it." },
        { name: "Search and filters", text: "By name, SKU or offer number; by status (active, inactive, ended); the sales period (30 days, 90 days, from the start); quick filters \"No picture\", \"No SKU\", \"No cost\", \"Not on Erli\" and \"Other category on Erli\"." },
        { name: "An offer's row", text: "Thumbnail, name, SKU and category, price, stock, pieces sold on Allegro and on Erli apart, the cost of making a piece, the margin and the status on Erli." },
        { name: "Margin", text: "Sales less Allegro's and Erli's fees for those orders less the cost of making the pieces sold, per piece, in all and as a share of the sales. The Allegro subscription is not counted. Until you enter a cost, the margin is \"before cost\"." },
        { name: "An opened row", text: "All the pictures (the copy on the server and a link to Allegro), the offer number with a link, the category on Allegro and on Erli with a verdict on whether they are the same, and a table of the sales for each marketplace apart." },
      ],
      actions: [
        "Type the cost of making a piece in the field of the row; Enter keeps it and goes to the next offer, Esc undoes it.",
        "Find the offers with no cost, picture or SKU and fill them in.",
        "Sort by pieces sold or margin to see what earns the most.",
        "Click \"Read from Allegro\" to refresh the assortment; the progress shows on a bar and the reading goes on in the background.",
      ],
      tips: [
        "The pictures are downloaded to the server once and kept beside their address on Allegro; the rest follow by themselves every quarter of an hour.",
        "The cost applies back in time: changing it changes every piece sold in the period chosen.",
      ],
    },
    {
      id: "labels",
      group: "daily",
      title: "Labels",
      path: "/labels",
      image: "labels",
      intro: "The bought labels in one place: you print them together and order a courier, and you make parcel locker shipments for InPost in bulk.",
      parts: [
        { name: "Wysyłam z Allegro", text: "The bought labels, oldest first, grouped by carrier (DPD, DHL, InPost…), with the views \"To print\", \"No courier ordered\" and \"All bought\". The selected labels print as one A6 PDF with the \"Print … labels\" button; \"Unselect group\" clears a whole carrier." },
        { name: "Test label", text: "The link at the top right opens a sample A6 label made by Anvero: nothing is bought or sent. Use it to check that the printer and the page settings are right." },
        { name: "Ordering a courier", text: "The selected parcels can be covered by one pickup order." },
        { name: "InPost", text: "The orders a parcel locker shipment can be made for, with a choice of size A, B or C. You make them together (up to 50 at once) and then print the labels." },
      ],
      actions: [
        "Print many labels with one click.",
        "Order a courier to collect the parcels.",
        "Make InPost shipments for several orders at once.",
        "See which labels have not been printed yet.",
      ],
      tips: [
        "Buying a label costs money (Allegro charges for it), so the application asks you to confirm. With safe mode on, nothing is really bought.",
        "A single label can also be bought on the order page, in \"Shipping\".",
      ],
    },
    {
      id: "after-sales",
      group: "daily",
      title: "Returns and claims",
      path: "/after-sales",
      image: "after-sales",
      intro: "The queue of returns, claims and disputes from Allegro, with deadlines, so none passes unnoticed.",
      parts: [
        { name: "Tiles", text: "How many cases wait for you, how many are past their deadline and how many are due within three days." },
        { name: "Views and kinds", text: "\"To do\" (the default, nearest deadline first), \"Open\" and \"All\", and a filter by kind: returns, claims, discussions." },
        { name: "A case's row", text: "The deadline (a coloured chip), the kind, what has to be done, the order with a link, the buyer, the reason, a short summary and the status." },
      ],
      actions: [
        "See what needs a decision or a reply, and by when.",
        "Go to the order the case is about.",
        "Click \"Read from Allegro\" to refresh the queue at once.",
      ],
      tips: [
        "A claim's deadline comes from Allegro. A return's does not, so it is worked out (14 days to decide, 45 to claim the commission back), deliberately a little early.",
        "For now it is a read-only view: you make the decisions in Allegro's panel.",
      ],
    },
    {
      id: "inbox",
      group: "daily",
      title: "Inbox",
      path: "/inbox",
      image: "inbox",
      intro: "Buyers' messages from Allegro in one inbox, so you do not switch between panels.",
      parts: [
        { name: "The list of threads", text: "Grouped by day (Today, Yesterday, Older) with the number of threads. A dot beside the login means an unread message, the \"waiting …\" chip says how long the buyer has waited for a reply (red after a day), and the \"Order\" chip leads to the order." },
        { name: "Tabs and the search", text: "\"To handle\" and \"Set aside\" with their counts; a search by login, order number or word, through the whole conversation." },
        { name: "The \"Check for new messages\" button", text: "Fetches new messages from Allegro at once; otherwise the application does it by itself." },
        { name: "The conversation", text: "The whole exchange, the reply box and a link to the order it concerns." },
      ],
      actions: [
        "Reply to a buyer (the reply reaches Allegro once safe mode is off).",
        "Set a thread aside for later and bring it back.",
        "Go from a message to its order.",
      ],
      tips: [
        "Erli does not offer messages through its API, so those have to be read in its panel.",
        "Messages are erased by themselves two years after the last message (GDPR).",
      ],
    },
    {
      id: "finance",
      group: "money",
      title: "Finance",
      path: "/finance",
      image: "finance",
      intro: "What was sold in the chosen period, what the marketplaces took and what is left.",
      parts: [
        { name: "Period", text: "This month, last month, 7, 30 or 90 days; the result is compared with the period before it of the same length." },
        { name: "The four tiles at the top", text: "Sales, Marketplace fees (with their share of the sales and a \"Show orders\" button), What is left after fees (before the cost of making) and What is left per order (on average)." },
        { name: "Where the fees went, By channel, Delivery", text: "The fees by kind and marketplace (with the direction of change), the split of sales and fees between Allegro and Erli, and what buyers paid for delivery against what the marketplace charged." },
        { name: "Agreement with the marketplace", text: "A check that the fees Anvero knows agree with what the marketplace took from the payouts, and how much it has not yet taken." },
        { name: "Products", text: "Each product sold with its share of the fees of the orders it was in." },
        { name: "Orders and their fees", text: "A section (\"Show orders\") that opens to the orders of the period with the fees charged for each; more can be shown." },
      ],
      actions: [
        "See how much the commissions cost in a month and whether they are growing.",
        "Find the products the fees eat the most of.",
        "Compare the fees with the payouts from Allegro and Erli.",
      ],
      tips: ["Allegro's subscription is among the month's fees, but is not added to any product or order."],
    },
    {
      id: "sales-report",
      group: "money",
      title: "Sales report",
      path: "/sales-report",
      image: "sales-report",
      intro: "The record of sales exempt from the cash register (poz. 41) and the report for the accountant: what the law requires for mail-order sales to private buyers without an invoice.",
      parts: [
        { name: "Period and export", text: "Date fields with the \"Last month\" and \"This month\" buttons, and the CSV, Excel and PDF buttons at the top, with a choice of columns." },
        { name: "Tiles", text: "All, In the record, To decide, Needs the cash register and Outside the record. Every sale is classified by itself after each import." },
        { name: "The list of rows", text: "The payment date, the order, the buyer with an address, the amount, the payment operator and the reason for the classification; a row \"To decide\" can be settled with a written reason." },
        { name: "The VAT exemption limit", text: "A bar showing how much of the year's VAT exemption limit is used, with a warning when it is close; and the matters to look at before the report is handed over." },
        { name: "The report for the accountant", text: "The report for a chosen date range, exported to CSV, Excel or PDF with the columns chosen. \"Hand over to the accountant\" closes the report: its rows will not change again." },
      ],
      actions: [
        "Choose a date range and download the report in the format needed.",
        "Settle the sales \"To decide\" by giving a reason.",
        "Hand the report over to the accountant; a later change becomes a correction, not a change to the handed-over report.",
      ],
      tips: [
        "The buyer's data in the record is erased after the retention period (five years after the tax year); the amounts stay.",
      ],
    },
    {
      id: "settings",
      group: "setup",
      title: "Settings: general",
      path: "/settings",
      image: "settings",
      intro: "What belongs to the application itself: safe mode, the look and language, and the GDPR controller's details.",
      parts: [
        { name: "Safe mode", text: "The switch and a log of what was sent, or would have been sent, to Allegro and Erli. Switching it off asks for confirmation, because from then on changes reach the buyers for real." },
        { name: "Appearance and language", text: "The style (Classic or Papier), light or dark mode and the language of the interface; saved in this browser." },
        { name: "Data controller (GDPR)", text: "The company's details put into the notice to buyers and the register; visible to an administrator." },
      ],
      actions: [
        "Check in the log what the application would send before switching safe mode off.",
        "Change the look and the language.",
        "Fill in the controller's details so the notice to buyers is complete.",
      ],
      adminOnly: false,
    },
    {
      id: "integrations",
      group: "setup",
      title: "Settings: integrations",
      path: "/settings?tab=integrations",
      image: "integrations",
      intro: "The connections to Allegro, Erli and InPost, and the sender's details and the default parcel.",
      parts: [
        { name: "Automatic update", text: "How many minutes between the times the application fetches orders and messages from every channel by itself (0 switches it off). A change takes effect within half a minute." },
        { name: "Tiles", text: "Allegro, Erli, InPost and \"Sender and parcel\", each with its state of connection and last import. A click opens the form below." },
        { name: "The form", text: "Allegro: connecting the account and the application's details; Erli: the API key; InPost: the token, organization and environment; Sender: the details and the default parcel size." },
      ],
      actions: [
        "Connect the Allegro account or enter the Erli key and check it was accepted.",
        "Change how often the imports run.",
        "Enter the sender's details and the default parcel for labels.",
      ],
      tips: ["Tokens and keys are never shown in full or saved in Git. An administrator is needed to set them."],
    },
    {
      id: "users",
      group: "setup",
      title: "Settings: users",
      path: "/settings?tab=users",
      image: "users",
      intro: "The accounts of the people working in the application and what each can reach. For an administrator only.",
      parts: [
        { name: "The list of accounts", text: "The accounts with a role (administrator or user) and a state (active or not)." },
        { name: "The account form", text: "The role, the state and the permissions for the areas: orders and production, messages, returns and claims, labels and couriers, finance and reports, integrations and safe mode. Each area has the level \"view\" or \"manage\"." },
      ],
      actions: [
        "Add a colleague's account and give it only the permissions needed.",
        "Switch off the account of someone who has left.",
        "Change an account's password.",
      ],
      tips: ["An administrator can reach everything. The application will not let the system be left without an active administrator."],
      adminOnly: true,
    },
    {
      id: "updates",
      group: "setup",
      title: "Settings: updates",
      path: "/settings?tab=updates",
      image: "updates",
      intro: "The application's version and installing new ones. For an administrator only.",
      parts: [
        { name: "The version card", text: "Says in its head whether a new version waits, with the list of changes; the install button is at the foot of the card." },
        { name: "History", text: "The earlier updates with their date and result." },
      ],
      actions: ["Install a new version with the button (the application is away for a moment, then returns).", "See what the previous update changed."],
      adminOnly: true,
    },
    {
      id: "status",
      group: "setup",
      title: "Settings: app status",
      path: "/settings?tab=status",
      image: "status",
      intro: "Is everything working: the connections to the marketplaces, the last imports and the schedule. Look here when something seems wrong.",
      parts: [
        { name: "The bar at the top", text: "The colour of the worst state and a description of what is wrong and where to put it right; \"Check again\" refreshes it." },
        { name: "The tiles", text: "Allegro, Erli and the application itself: the state of the connection, the last import, the next import and the message sync." },
        { name: "Latest events", text: "What happened: imports, errors, changes." },
      ],
      actions: ["Check whether the last import worked.", "See when the next one is.", "Go to Integrations when a connection has expired."],
      tips: ["An orange dot beside Settings in the menu means this screen has something to show."],
    },
    {
      id: "help",
      group: "setup",
      title: "Help: the guide and GDPR",
      path: "/help",
      image: "help",
      intro: "This page. The guide describes the parts of the application, and the GDPR tab holds what you need to know and to have about personal data.",
      parts: [
        { name: "The guide", text: "A list of the parts, a short \"where do I find…\" cheat sheet and a glossary." },
        { name: "GDPR", text: "The controller's details, a ready notice to buyers, what we process, how to handle a request, what to do after a breach, and the register of processing activities to print." },
      ],
      actions: ["Find a part by what you want to do.", "Copy the notice to buyers.", "Print the register of processing activities."],
    },
  ],
  lookup: [
    { question: "see what to send today", answer: "Dashboard or Orders, the \"To ship\" queue", path: "/orders?queue=to_ship" },
    { question: "see what is past its deadline", answer: "Orders, the \"Past deadline\" queue", path: "/orders?queue=late" },
    { question: "know what to make", answer: "To make", path: "/production" },
    { question: "find an order by a name, number or parcel", answer: "Orders, the search at the top", path: "/orders" },
    { question: "add a tracking number", answer: "The order → Shipping → \"Own number\"", path: "/orders" },
    { question: "buy or print a label", answer: "The order → Shipping (one), or Labels (many at once)", path: "/labels" },
    { question: "reply to a buyer", answer: "Inbox", path: "/inbox" },
    { question: "check a return or claim and its deadline", answer: "Returns and claims", path: "/after-sales" },
    { question: "know what we earn on a product", answer: "Assortment, the \"Margin\" column", path: "/catalog" },
    { question: "enter what making a product costs", answer: "Assortment, the \"Cost / pc\" field in the offer's row", path: "/catalog" },
    { question: "check what the commissions came to", answer: "Finance", path: "/finance" },
    { question: "prepare the report for the accountant", answer: "Sales report", path: "/sales-report" },
    { question: "check that Allegro and Erli are working", answer: "Settings → App status", path: "/settings?tab=status" },
    { question: "add a colleague's account", answer: "Settings → Users (administrator)", path: "/settings?tab=users" },
    { question: "update the application", answer: "Settings → Updates (administrator)", path: "/settings?tab=updates" },
    { question: "change the language or the look", answer: "The foot of the menu, or Settings → General", path: "/settings" },
    { question: "handle a buyer's request about their data (GDPR)", answer: "Help → GDPR → \"How to handle a request\"", path: "/help?tab=gdpr" },
  ],
  glossary: [
    { term: "Channel, source", text: "The marketplace an order came from: Allegro (the letter A) or Erli (the letter E)." },
    { term: "Offer", text: "An item listed on Allegro or Erli. The same offer has an offer number on the marketplace and may have a SKU of its own." },
    { term: "SKU", text: "The seller's own product code. It lets the same product be recognized on different marketplaces." },
    { term: "Order status", text: "New, In progress, Ready to ship, Shipped, Delivered or Cancelled. The status changes from the marketplace (after dispatch, say) or by hand." },
    { term: "Work queue", text: "A ready filter of the order list: To make, Unpaid, To ship, Past deadline, Starred, Flagged." },
    { term: "Dispatch deadline", text: "By when an order must be sent. Allegro gives it, Erli does not, so Erli orders are never \"past deadline\"." },
    { term: "Import", text: "Fetching orders (and other data) from Allegro or Erli. It happens by itself every few minutes, or on a button." },
    { term: "Safe mode", text: "While it is on, Anvero sends nothing to the marketplaces and only records what it would have sent. Recommended at the start and while trying things." },
    { term: "Label", text: "The parcel's document. Allegro: \"Wysyłam z Allegro\" (bought in the application, paid); InPost: a parcel locker shipment made through the API." },
    { term: "Margin", text: "Sales less the marketplace's fees less the cost of making the pieces sold. With no cost entered it is the margin \"before cost\"." },
    { term: "Sales report (non-invoiced)", text: "The record of sales to private buyers exempt from the cash register (poz. 41) and the report for the accountant." },
    { term: "Anonymization", text: "Removing the personal data from an order after the retention period; the order stays for the statistics, without the buyer's data." },
  ],
};
