import type { GuideContent } from "./types";

/** Przewodnik po aplikacji, po polsku. Opisuje to, co faktycznie jest na ekranach (docs/GUIDE.md). */
export const guidePl: GuideContent = {
  about:
    "Anvero zbiera zamówienia z Allegro i Erli w jednym miejscu i prowadzi je od przyjęcia do wysyłki: widać, co zrobić, co zapakować, co wysłać i co się spóźnia, można kupić etykiety, odpowiedzieć kupującym, sprawdzić opłaty i marżę oraz przygotować raport dla księgowej. Aplikacja czyta dane z Allegro i Erli, a to, co sama zmienia, wysyła do nich dopiero po wyłączeniu trybu bezpiecznego.",
  groups: {
    basics: "Podstawy",
    daily: "Codzienna praca",
    money: "Pieniądze i rozliczenia",
    setup: "Ustawienia i administracja",
  },
  sections: [
    {
      id: "start",
      group: "basics",
      title: "Pierwsze kroki: menu i podstawy",
      path: "/dashboard",
      image: "menu",
      intro:
        "Po zalogowaniu widzisz menu po lewej, a w nim wszystkie działy. Liczby przy pozycjach mówią, co na Ciebie czeka, więc często nie trzeba nigdzie wchodzić, żeby wiedzieć, od czego zacząć.",
      parts: [
        { name: "Menu po lewej", text: "Pulpit, Zamówienia, Do wykonania, Asortyment, Etykiety, Zwroty i reklamacje, Wiadomości, Finanse, Raport bezrachunkowy, Ustawienia i Pomoc. Strzałka na górze zwija je do samych ikon. Pod pozycją „Zamówienia” rozwija się lista statusów i kanałów z liczbami zamówień." },
        { name: "Liczby przy pozycjach", text: "Ile zamówień czeka na wysyłkę (czerwona, gdy któreś jest po terminie), ile pozycji do wykonania, ile spraw zwrotów i reklamacji, ile nieprzeczytanych wiadomości. Pomarańczowa kropka przy Ustawieniach oznacza, że coś w stanie aplikacji wymaga uwagi." },
        { name: "Pasek „Tryb bezpieczny”", text: "Zielony pasek nad stroną: dopóki jest, Anvero nic nie wysyła do Allegro ani Erli, a zmiany tylko zapisuje. Zmiany statusu, numery przesyłek i odpowiedzi trafią do marketplace'ów dopiero po wyłączeniu trybu w Ustawieniach." },
        { name: "Dół menu", text: "Przełącznik języka (polski i angielski), jasny i ciemny motyw oraz „Wyloguj”. Wygląd aplikacji (styl Classic lub Papier) zmieniasz w Ustawieniach." },
      ],
      actions: [
        "Przejść do działu kliknięciem w menu lub w kafelek na Pulpicie.",
        "Zwinąć menu, żeby dać więcej miejsca tabelom.",
        "Zmienić język i motyw bez wychodzenia ze strony.",
      ],
      tips: [
        "Widzisz tylko te działy, do których administrator dał Ci dostęp (Ustawienia → Użytkownicy). Brak pozycji w menu zwykle oznacza brak uprawnienia, a nie błąd.",
        "Nowa osoba nie musi niczego konfigurować: integracje z Allegro i Erli, harmonogram importów i tryb bezpieczny ustawia administrator.",
      ],
    },
    {
      id: "dashboard",
      group: "daily",
      title: "Pulpit",
      path: "/dashboard",
      image: "dashboard",
      intro: "Strona startowa: co czeka, co się pali i jak idzie sprzedaż, na jednym ekranie.",
      parts: [
        { name: "Czeka na Ciebie", text: "Kafelki kolejek: Do wykonania, Nieopłacone, Do wysłania i Po terminie, każdy z liczbą. Kliknięcie otwiera listę zamówień już przefiltrowaną do tej kolejki." },
        { name: "Wymaga uwagi", text: "Rzeczy, których nie wolno przegapić: zamówienia anulowane na marketplace, ale wciąż aktywne tutaj, problemy ze stanem aplikacji i nieprzeczytane wiadomości od kupujących." },
        { name: "W skrócie", text: "Zamówienia z tego tygodnia, przychód i liczba zamówień w realizacji, oraz podział na kanały sprzedaży (Allegro, Erli)." },
        { name: "Najbliższe terminy wysyłki", text: "Zamówienia z najbliższym terminem nadania, z informacją, ile czasu zostało albo o ile się spóźniają." },
        { name: "Ostatnie zamówienia", text: "Najnowsze zamówienia z kanałem, kupującym, statusem i kwotą; numer otwiera zamówienie." },
      ],
      actions: [
        "Zacząć dzień od kafelka „Po terminie” i „Do wysłania”.",
        "Wejść w zamówienie z listy ostatnich lub z listy terminów.",
        "Przejść do stanu aplikacji, gdy pojawi się ostrzeżenie.",
      ],
    },
    {
      id: "orders",
      group: "daily",
      title: "Zamówienia",
      path: "/orders",
      image: "orders",
      intro: "Lista wszystkich zamówień z Allegro i Erli. To tutaj szukasz zamówienia, filtrujesz je i pracujesz na wielu naraz.",
      parts: [
        { name: "Kolejki pracy", text: "Wszystkie, Do wykonania, Nieopłacone, Do wysłania, Po terminie, Z gwiazdką i Z flagą. Obok filtr statusu (Nowe, W realizacji, Gotowe do wysyłki, Wysłane, Dostarczone, Anulowane) i kanału." },
        { name: "Wyszukiwarka i filtry", text: "Szuka po numerze zamówienia, kupującym, produkcie lub SKU, mieście, paczkomacie i numerze przesyłki. „Filtry” dodają źródło, status i zakres dat. Wpisana fraza nie zostaje w adresie strony ani w historii przeglądarki." },
        { name: "Pasek importów", text: "Pokazuje, kiedy ostatnio pobrano zamówienia z Allegro i z Erli i ile było nowych. Przycisk „Importuj zamówienia” pobiera je od razu; poza tym aplikacja robi to sama co kilkanaście minut." },
        { name: "Tabela", text: "Numer Anvero (AN-000123) i numer na marketplace, pozycje ze zdjęciem, kupujący, status, wysyłka (przewoźnik, numer, śledzenie), kwota i forma płatności, oznaczenia (gwiazdka, flaga, notatka)." },
        { name: "Sortowanie", text: "Najnowsze, Najstarsze lub „Zagrożone najpierw” (te z najkrótszym czasem do terminu)." },
      ],
      actions: [
        "Otworzyć zamówienie kliknięciem w jego wiersz.",
        "Zaznaczyć kilka zamówień i zmienić im status albo dodać gwiazdkę lub flagę naraz.",
        "Oznaczyć zamówienie gwiazdką lub flagą, żeby łatwo je znaleźć później.",
        "Wrócić do listy z zachowanymi filtrami po obejrzeniu zamówienia (strzałki „poprzednie” i „następne” na stronie zamówienia).",
      ],
      tips: [
        "Zamówienie anulowane na Allegro lub Erli dostaje ostrzeżenie, dopóki go tu nie obsłużysz. Sprawdź je przed pakowaniem.",
        "Usuniętego zamówienia nie trzeba się bać: można je przywrócić ze strony zamówienia.",
      ],
    },
    {
      id: "order",
      group: "daily",
      title: "Strona zamówienia",
      path: "/orders",
      image: "order",
      intro: "Wszystko o jednym zamówieniu: co kupiono, kto, dokąd, jak zapłacił, co z przesyłką i co się z nim działo.",
      parts: [
        { name: "Nagłówek i kolejny krok", text: "Numer, kanał, status i przycisk „Oznacz jako…”, który przesuwa zamówienie o jeden etap. Strzałki obok przechodzą do poprzedniego i następnego zamówienia z listy." },
        { name: "Pozycje", text: "Produkty z ilością i ceną. Przyciskami „−” i „+” w kolumnie „Spakowano” oznaczasz sztuki jako spakowane; nagłówek pokazuje, ile z ilu jest gotowe." },
        { name: "Wysyłka", text: "Przesyłki zamówienia ze śledzeniem. Numer dodasz na zakładce „Własny numer”, kupisz etykietę w „Etykieta Allegro” albo utworzysz przesyłkę do paczkomatu w „InPost”." },
        { name: "Notatka wewnętrzna", text: "Pole na Twoją notatkę. Jest tylko w Anvero: kupujący ani marketplace jej nie widzą." },
        { name: "Wiersze rozwijane pod notatką", text: "Historia statusów (kto i kiedy zmienił), Opłaty marketplace'u (prowizje i inne opłaty za to zamówienie oraz to, co z niego zostaje), Inne zamówienia kupującego i Dane techniczne." },
        { name: "Kolumna po prawej", text: "Kupujący (dane i login na marketplace), Dostawa (sposób, punkt odbioru lub adres odbiorcy, przycisk kopiowania adresu), Faktura (czy kupujący o nią prosił) i Płatność (czy i kiedy zapłacono)." },
        { name: "Wiadomości i zwroty", text: "Gdy kupujący pisał albo jest sprawa zwrotu lub reklamacji, pojawia się karta z rozmową, polem odpowiedzi i terminami." },
      ],
      actions: [
        "Przesunąć zamówienie dalej przyciskiem „Oznacz jako…” albo wybrać status z listy.",
        "Zmienić status i dodać numer przesyłki; po wyłączeniu trybu bezpiecznego trafią one do Allegro i Erli.",
        "Kupić etykietę lub utworzyć przesyłkę InPost bez wychodzenia z zamówienia.",
        "Zapisać własną notatkę, której nie widzi nikt poza zespołem.",
        "Usunąć zamówienie i je przywrócić.",
      ],
      tips: [
        "Dane osobowe w zamówieniach są automatycznie anonimizowane po okresie przechowywania. Zamówienie wtedy zostaje (kwoty, pozycje), ale bez danych kupującego. Więcej w Pomoc → RODO.",
      ],
    },
    {
      id: "production",
      group: "daily",
      title: "Do wykonania",
      path: "/production",
      image: "production",
      intro: "Lista dla warsztatu: co wykonać i w jakiej ilości dla opłaconych zamówień, które jeszcze czekają, od najpilniejszych.",
      parts: [
        { name: "Grupy", text: "Produkty pogrupowane według dnia, do którego zamówienia muszą wyjść: po terminie, dziś, jutro, dalsze dni i bez terminu. Każda grupa pokazuje, ile już zrobiono." },
        { name: "Wiersz produktu", text: "Ilość do wykonania, zdjęcie (po najechaniu powiększa się), nazwa i SKU oraz zamówienia, których produkt dotyczy." },
        { name: "Pasek na górze", text: "Filtr statusu (Wszystkie, Nowe, W realizacji), „Ukryj zrobione”, wyszukiwarka (po numerze zamówienia, loginie, nazwisku lub produkcie; kilka fraz po przecinku) oraz podsumowanie postępu w sztukach, produktach i zamówieniach." },
      ],
      actions: [
        "Odhaczać produkty, gdy są zrobione; odhaczenie widzą wszyscy korzystający z tej bazy.",
        "Ukryć zrobione, żeby zobaczyć tylko to, co zostało.",
        "Wydrukować listę przyciskiem „Drukuj”.",
        "Przejść z produktu do jego zamówienia.",
      ],
    },
    {
      id: "catalog",
      group: "daily",
      title: "Asortyment",
      path: "/catalog",
      image: "catalog",
      intro: "Wszystkie oferty z konta Allegro, razem ze zdjęciami, sprzedażą i marżą, oraz informacja, jak ten sam produkt wygląda na Erli. Tylko do odczytu: nic stąd nie zmienia ofert na marketplace.",
      parts: [
        { name: "Kategorie", text: "Rząd przycisków nad listą: kategorie z Allegro z liczbą ofert. Kliknięcie wybiera kategorię i pokazuje oferty w niej i we wszystkich pod nią, a pod spodem pojawia się rząd jej podkategorii. Ponowne kliknięcie wybranej wraca o poziom wyżej, a „Wszystkie kategorie” zdejmuje wybór." },
        { name: "Wyszukiwanie i filtry", text: "Po nazwie, SKU lub numerze oferty; status (aktywne, nieaktywne, zakończone); okres sprzedaży (30 dni, 90 dni, od początku); szybkie filtry „Brak zdjęcia”, „Bez SKU”, „Bez kosztu”, „Nie ma na Erli” i „Inna kategoria na Erli”." },
        { name: "Wiersz oferty", text: "Miniatura, nazwa, SKU i kategoria, cena, stan magazynowy, sprzedane sztuki osobno na Allegro i Erli, koszt wytworzenia sztuki, marża i status na Erli." },
        { name: "Marża", text: "Sprzedaż minus opłaty Allegro i Erli za te zamówienia minus koszt wytworzenia sprzedanych sztuk, na sztukę, łącznie i jako procent sprzedaży. Abonament Allegro nie jest wliczany. Dopóki nie wpiszesz kosztu, marża jest „przed kosztem”." },
        { name: "Rozwinięty wiersz", text: "Wszystkie zdjęcia (kopia na serwerze i link do Allegro), numer oferty z linkiem, kategoria w Allegro i na Erli z oceną, czy są takie same, oraz tabela sprzedaży osobno dla obu marketplace'ów." },
      ],
      actions: [
        "Wpisać koszt wytworzenia sztuki w polu w wierszu; Enter zapisuje i przechodzi do następnej oferty, Esc cofa.",
        "Znaleźć oferty bez kosztu, bez zdjęcia lub bez SKU i je uzupełnić.",
        "Posortować po sprzedanych sztukach lub marży, żeby zobaczyć, co najlepiej zarabia.",
        "Kliknąć „Pobierz z Allegro”, żeby odświeżyć asortyment; postęp widać na pasku, a pobieranie trwa w tle.",
      ],
      tips: [
        "Zdjęcia są pobierane na serwer raz i trzymane obok adresu w Allegro; reszta dociąga się sama co kilkanaście minut.",
        "Koszt obowiązuje wstecz: zmieniasz go dla wszystkich sprzedanych sztuk z wybranego okresu.",
      ],
    },
    {
      id: "labels",
      group: "daily",
      title: "Etykiety",
      path: "/labels",
      image: "labels",
      intro: "Kupione etykiety w jednym miejscu: drukujesz je naraz i zamawiasz kuriera, a przesyłki do paczkomatów InPost tworzysz hurtem.",
      parts: [
        { name: "Wysyłam z Allegro", text: "Kupione etykiety od najstarszej, pogrupowane według przewoźnika (DPD, DHL, InPost…), z widokami „Do wydruku”, „Bez zamówionego kuriera” i „Wszystkie kupione”. Zaznaczone etykiety drukujesz przyciskiem „Drukuj … etykiety” jako jeden plik PDF w formacie A6; „Odznacz grupę” zdejmuje zaznaczenie z całego przewoźnika." },
        { name: "Testowa etykieta", text: "Link u góry po prawej otwiera przykładową etykietę A6 wykonaną przez Anvero: nic nie jest kupowane ani wysyłane. Sprawdzisz nią, czy drukarka i ustawienia strony są dobre." },
        { name: "Zamówienie kuriera", text: "Zaznaczone przesyłki możesz objąć jednym zamówieniem odbioru przez kuriera." },
        { name: "InPost", text: "Zamówienia, dla których można utworzyć przesyłkę do paczkomatu, z wyborem rozmiaru A, B lub C. Utworzysz je razem (do 50 naraz), a potem wydrukujesz etykiety." },
      ],
      actions: [
        "Wydrukować wiele etykiet jednym kliknięciem.",
        "Zamówić kuriera po odbiór paczek.",
        "Utworzyć przesyłki InPost dla kilku zamówień naraz.",
        "Zobaczyć, które etykiety nie zostały jeszcze wydrukowane.",
      ],
      tips: [
        "Kupno etykiety kosztuje (Allegro pobiera opłatę), więc aplikacja prosi o potwierdzenie. Przy włączonym trybie bezpiecznym nic nie jest kupowane naprawdę.",
        "Pojedynczą etykietę kupisz też na stronie zamówienia, w sekcji „Wysyłka”.",
      ],
    },
    {
      id: "after-sales",
      group: "daily",
      title: "Zwroty i reklamacje",
      path: "/after-sales",
      image: "after-sales",
      intro: "Kolejka zwrotów, reklamacji i sporów z Allegro, z terminami, żeby żaden nie minął niezauważony.",
      parts: [
        { name: "Kafelki", text: "Ile spraw czeka na Ciebie, ile jest po terminie i ile ma termin w ciągu trzech dni." },
        { name: "Widoki i rodzaje", text: "„Do zrobienia” (domyślnie, od najbliższego terminu), „Otwarte” i „Wszystkie”, oraz filtr rodzaju: zwroty, reklamacje, dyskusje." },
        { name: "Wiersz sprawy", text: "Termin (kolorowa plakietka), rodzaj, co trzeba zrobić, zamówienie z linkiem, kupujący, powód, krótkie streszczenie i status." },
      ],
      actions: [
        "Zobaczyć, co wymaga decyzji lub odpowiedzi i do kiedy.",
        "Przejść do zamówienia, którego sprawa dotyczy.",
        "Kliknąć „Wczytaj z Allegro”, żeby odświeżyć kolejkę od razu.",
      ],
      tips: [
        "Termin reklamacji podaje Allegro. Terminu zwrotu nie podaje, więc jest liczony (14 dni na decyzję, 45 na odzyskanie prowizji), celowo trochę z zapasem.",
        "Na razie to widok tylko do odczytu: decyzje podejmujesz w panelu Allegro.",
      ],
    },
    {
      id: "inbox",
      group: "daily",
      title: "Wiadomości",
      path: "/inbox",
      image: "inbox",
      intro: "Wiadomości od kupujących z Allegro w jednej skrzynce, żeby nie przełączać się między panelami.",
      parts: [
        { name: "Lista wątków", text: "Grupowana według dnia (Dziś, Wczoraj, Starsze) z liczbą wątków. Kropka przy loginie oznacza wiadomość nieprzeczytaną, plakietka „czeka …” mówi, jak długo kupujący czeka na odpowiedź (czerwona po dobie), a plakietka „Zamówienie” prowadzi do zamówienia." },
        { name: "Zakładki i wyszukiwarka", text: "„Do obsługi” i „Odłożone” z liczbą wątków; wyszukiwarka po loginie, numerze zamówienia lub słowie, w całej rozmowie." },
        { name: "Przycisk „Sprawdź nowe wiadomości”", text: "Pobiera nowe wiadomości z Allegro od razu; poza tym aplikacja robi to sama." },
        { name: "Rozmowa", text: "Cała wymiana wiadomości, pole odpowiedzi i link do zamówienia, którego dotyczy." },
      ],
      actions: [
        "Odpowiedzieć kupującemu (odpowiedź trafia do Allegro po wyłączeniu trybu bezpiecznego).",
        "Odłożyć wątek na później i go przywrócić.",
        "Przejść z wiadomości do zamówienia.",
      ],
      tips: [
        "Erli nie udostępnia wiadomości przez swoje API, więc te trzeba czytać w jego panelu.",
        "Wiadomości są automatycznie usuwane po dwóch latach od ostatniej wiadomości (RODO).",
      ],
    },
    {
      id: "finance",
      group: "money",
      title: "Finanse",
      path: "/finance",
      image: "finance",
      intro: "Co sprzedano w wybranym okresie, ile wzięły marketplace'y i co zostało.",
      parts: [
        { name: "Okres", text: "Ten miesiąc, poprzedni miesiąc, 7, 30 lub 90 dni; wynik jest porównany z poprzednim okresem o tej samej długości." },
        { name: "Cztery kafelki u góry", text: "Sprzedaż, Opłaty marketplace'ów (z udziałem w sprzedaży i przyciskiem „Pokaż zamówienia”), Zostaje po opłatach (przed kosztem wykonania) i Zostaje z zamówienia (średnio)." },
        { name: "Na co poszły opłaty, Według kanału, Dostawa", text: "Opłaty z podziałem na rodzaje i marketplace'y (z kierunkiem zmiany), podział sprzedaży i opłat na Allegro i Erli oraz to, ile kupujący zapłacili za dostawę, a ile pobrał marketplace." },
        { name: "Zgodność z marketplace'em", text: "Sprawdzenie, czy opłaty, które Anvero zna, zgadzają się z tym, co marketplace potrącił z wypłat, i ile jeszcze nie zostało pobrane." },
        { name: "Produkty", text: "Każdy sprzedany produkt z udziałem w opłatach zamówień, w których wystąpił." },
        { name: "Zamówienia i ich opłaty", text: "Rozwijana sekcja („Pokaż zamówienia”) z zamówieniami z okresu i opłatami naliczonymi za każde z nich; można pokazać kolejne." },
      ],
      actions: [
        "Sprawdzić, ile kosztowały prowizje w miesiącu i czy rosną.",
        "Znaleźć produkty, na których opłaty zjadają najwięcej.",
        "Porównać opłaty z wypłatami z Allegro i Erli.",
      ],
      tips: [
        "Abonament Allegro jest w opłatach miesiąca, ale nie jest doliczany do żadnego produktu ani zamówienia.",
      ],
    },
    {
      id: "sales-report",
      group: "money",
      title: "Raport bezrachunkowy",
      path: "/sales-report",
      image: "sales-report",
      intro: "Ewidencja sprzedaży zwolnionej z kasy rejestrującej (poz. 41) oraz raport dla księgowej: to, co prawo każe prowadzić dla sprzedaży wysyłkowej do osób prywatnych bez faktury.",
      parts: [
        { name: "Okres i eksport", text: "Pola dat z przyciskami „Poprzedni miesiąc” i „Ten miesiąc” oraz przyciski CSV, Excel i PDF u góry, z wyborem kolumn." },
        { name: "Kafelki", text: "Wszystkie, Do ewidencji, Do decyzji, Wymaga kasy i Poza ewidencją. Każda sprzedaż jest automatycznie klasyfikowana po każdym imporcie." },
        { name: "Lista wierszy", text: "Data zapłaty, zamówienie, kupujący z adresem, kwota, operator płatności i powód klasyfikacji; wiersz „Do decyzji” możesz rozstrzygnąć z zapisanym uzasadnieniem." },
        { name: "Limit zwolnienia z VAT", text: "Pasek pokazujący, ile z rocznego limitu zwolnienia z VAT już wykorzystano, z ostrzeżeniem, gdy jest blisko; oraz sprawy, które trzeba obejrzeć przed przekazaniem raportu." },
        { name: "Raport dla księgowej", text: "Raport za wybrany zakres dat z eksportem do CSV, Excela lub PDF, z wybranymi kolumnami. „Przekaż księgowej” zamyka raport: jego wiersze już się nie zmienią." },
      ],
      actions: [
        "Wybrać zakres dat i pobrać raport w potrzebnym formacie.",
        "Rozstrzygnąć sprzedaże „Do decyzji”, wpisując powód.",
        "Przekazać raport księgowej; kolejna zmiana stanie się korektą, a nie zmianą przekazanego raportu.",
      ],
      tips: [
        "Dane kupującego w ewidencji są usuwane po okresie przechowywania (pięć lat po roku podatkowym), a kwoty zostają.",
      ],
    },
    {
      id: "settings",
      group: "setup",
      title: "Ustawienia: ogólne",
      path: "/settings",
      image: "settings",
      intro: "Rzeczy dotyczące samej aplikacji: tryb bezpieczny, wygląd i język oraz dane administratora RODO.",
      parts: [
        { name: "Tryb bezpieczny", text: "Włącznik i dziennik tego, co zostało wysłane albo by zostało wysłane do Allegro i Erli. Wyłączenie wymaga potwierdzenia, bo od tej chwili zmiany trafiają do kupujących naprawdę." },
        { name: "Wygląd i język", text: "Styl (Classic lub Papier), motyw jasny lub ciemny i język interfejsu; zapisywane w tej przeglądarce." },
        { name: "Administrator danych (RODO)", text: "Dane firmy wstawiane do klauzuli informacyjnej i rejestru; widoczne dla administratora." },
      ],
      actions: [
        "Sprawdzić w dzienniku, co aplikacja by wysłała, zanim wyłączysz tryb bezpieczny.",
        "Zmienić wygląd i język.",
        "Uzupełnić dane administratora, żeby klauzula dla kupujących była kompletna.",
      ],
      adminOnly: false,
    },
    {
      id: "integrations",
      group: "setup",
      title: "Ustawienia: integracje",
      path: "/settings?tab=integrations",
      image: "integrations",
      intro: "Połączenia z Allegro, Erli i InPost oraz dane nadawcy i domyślna paczka.",
      parts: [
        { name: "Automatyczna aktualizacja", text: "Co ile minut aplikacja sama pobiera zamówienia i wiadomości ze wszystkich kanałów (0 wyłącza). Zmiana działa w ciągu pół minuty." },
        { name: "Kafelki", text: "Allegro, Erli, InPost oraz „Nadawca i paczka”, każdy ze stanem połączenia i ostatnim importem. Kliknięcie otwiera formularz pod spodem." },
        { name: "Formularz", text: "Allegro: połączenie konta i dane aplikacji; Erli: klucz API; InPost: token, organizacja i środowisko; Nadawca: dane i domyślne wymiary paczki." },
      ],
      actions: [
        "Połączyć konto Allegro lub podać klucz Erli i sprawdzić, czy zostało zaakceptowane.",
        "Zmienić częstotliwość importów.",
        "Podać dane nadawcy i domyślną paczkę do etykiet.",
      ],
      tips: ["Tokeny i klucze nigdy nie są pokazywane w całości ani zapisywane w Git. Do ustawienia ich potrzebny jest administrator."],
    },
    {
      id: "users",
      group: "setup",
      title: "Ustawienia: użytkownicy",
      path: "/settings?tab=users",
      image: "users",
      intro: "Konta osób pracujących w aplikacji i to, do czego każda ma dostęp. Tylko dla administratora.",
      parts: [
        { name: "Lista kont", text: "Konta z rolą (administrator lub użytkownik) i stanem (aktywne lub nie)." },
        { name: "Formularz konta", text: "Rola, stan i uprawnienia do obszarów: zamówienia i produkcja, wiadomości, zwroty i reklamacje, etykiety i kurierzy, finanse i raporty, integracje i tryb bezpieczny. Każdy obszar ma poziom „podgląd” albo „zarządzanie”." },
      ],
      actions: [
        "Dodać konto współpracownika i nadać mu tylko potrzebne uprawnienia.",
        "Wyłączyć konto osoby, która odeszła.",
        "Zmienić hasło konta.",
      ],
      tips: ["Administrator ma dostęp do wszystkiego. Aplikacja nie pozwoli zostawić systemu bez aktywnego administratora."],
      adminOnly: true,
    },
    {
      id: "updates",
      group: "setup",
      title: "Ustawienia: aktualizacje",
      path: "/settings?tab=updates",
      image: "updates",
      intro: "Wersja aplikacji i instalowanie nowych. Tylko dla administratora.",
      parts: [
        { name: "Karta wersji", text: "Mówi w nagłówku, czy czeka nowa wersja, z listą zmian; przycisk instalacji jest na dole karty." },
        { name: "Historia", text: "Wcześniejsze aktualizacje z datą i wynikiem." },
      ],
      actions: ["Zainstalować nową wersję przyciskiem (aplikacja chwilę nie odpowiada, po czym wraca).", "Zobaczyć, co zmieniła poprzednia aktualizacja."],
      adminOnly: true,
    },
    {
      id: "status",
      group: "setup",
      title: "Ustawienia: stan aplikacji",
      path: "/settings?tab=status",
      image: "status",
      intro: "Czy wszystko działa: połączenia z marketplace'ami, ostatnie importy i harmonogram. Zajrzyj tu, gdy coś wygląda nie tak.",
      parts: [
        { name: "Pasek na górze", text: "Kolor najgorszego stanu i opis, co jest nie tak i gdzie to poprawić; „Sprawdź ponownie” odświeża." },
        { name: "Kafelki", text: "Allegro, Erli i sama aplikacja: stan połączenia, ostatni import, następny import i synchronizacja wiadomości." },
        { name: "Ostatnie zdarzenia", text: "Co się wydarzyło: importy, błędy, zmiany." },
      ],
      actions: ["Sprawdzić, czy ostatni import się udał.", "Zobaczyć, kiedy będzie następny.", "Przejść do Integracji, gdy połączenie wygasło."],
      tips: ["Pomarańczowa kropka przy Ustawieniach w menu oznacza, że ten ekran ma coś do pokazania."],
    },
    {
      id: "help",
      group: "setup",
      title: "Pomoc: przewodnik i RODO",
      path: "/help",
      image: "help",
      intro: "Ta strona. Przewodnik opisuje działy aplikacji, a zakładka RODO zawiera to, co trzeba wiedzieć i mieć w związku z danymi osobowymi.",
      parts: [
        { name: "Przewodnik", text: "Spis działów, krótka ściąga „gdzie znajdę…” i słowniczek pojęć." },
        { name: "RODO", text: "Dane administratora, gotowa klauzula informacyjna dla kupujących, to, co przetwarzamy, jak obsłużyć wniosek, co robić przy naruszeniu oraz rejestr czynności przetwarzania do wydruku." },
      ],
      actions: ["Znaleźć dział po tym, co chcesz zrobić.", "Skopiować klauzulę dla kupujących.", "Wydrukować rejestr czynności przetwarzania."],
    },
  ],
  lookup: [
    { question: "zobaczyć, co dziś wysłać", answer: "Pulpit lub Zamówienia, kolejka „Do wysłania”", path: "/orders?queue=to_ship" },
    { question: "zobaczyć, co jest po terminie", answer: "Zamówienia, kolejka „Po terminie”", path: "/orders?queue=late" },
    { question: "wiedzieć, co wykonać", answer: "Do wykonania", path: "/production" },
    { question: "znaleźć zamówienie po nazwisku, numerze lub paczce", answer: "Zamówienia, wyszukiwarka na górze", path: "/orders" },
    { question: "dodać numer przesyłki", answer: "Zamówienie → Wysyłka → „Własny numer”", path: "/orders" },
    { question: "kupić lub wydrukować etykietę", answer: "Zamówienie → Wysyłka (jedna), albo Etykiety (wiele naraz)", path: "/labels" },
    { question: "odpowiedzieć kupującemu", answer: "Wiadomości", path: "/inbox" },
    { question: "sprawdzić zwrot lub reklamację i jej termin", answer: "Zwroty i reklamacje", path: "/after-sales" },
    { question: "wiedzieć, ile zarabiamy na produkcie", answer: "Asortyment, kolumna „Marża”", path: "/catalog" },
    { question: "wpisać koszt wytworzenia produktu", answer: "Asortyment, pole „Koszt / szt.” w wierszu oferty", path: "/catalog" },
    { question: "sprawdzić, ile wzięły prowizje", answer: "Finanse", path: "/finance" },
    { question: "przygotować raport dla księgowej", answer: "Raport bezrachunkowy", path: "/sales-report" },
    { question: "sprawdzić, czy Allegro i Erli działają", answer: "Ustawienia → Stan aplikacji", path: "/settings?tab=status" },
    { question: "dodać konto współpracownika", answer: "Ustawienia → Użytkownicy (administrator)", path: "/settings?tab=users" },
    { question: "zaktualizować aplikację", answer: "Ustawienia → Aktualizacje (administrator)", path: "/settings?tab=updates" },
    { question: "zmienić język lub wygląd", answer: "Menu na dole lub Ustawienia → Ogólne", path: "/settings" },
    { question: "obsłużyć wniosek kupującego o jego dane (RODO)", answer: "Pomoc → RODO → „Jak obsłużyć wniosek”", path: "/help?tab=gdpr" },
  ],
  glossary: [
    { term: "Kanał, źródło", text: "Marketplace, z którego przyszło zamówienie: Allegro (litera A) lub Erli (litera E)." },
    { term: "Oferta", text: "Pozycja wystawiona na Allegro lub Erli. Ta sama oferta ma numer oferty na marketplace i może mieć własny kod SKU." },
    { term: "SKU", text: "Własny kod produktu sprzedawcy. Pozwala rozpoznać ten sam produkt na różnych marketplace'ach." },
    { term: "Status zamówienia", text: "Nowe, W realizacji, Gotowe do wysyłki, Wysłane, Dostarczone lub Anulowane. Status zmienia się z marketplace'u (np. po nadaniu) albo ręcznie." },
    { term: "Kolejka pracy", text: "Gotowy filtr listy zamówień: Do wykonania, Nieopłacone, Do wysłania, Po terminie, z gwiazdką, z flagą." },
    { term: "Termin wysyłki", text: "Do kiedy zamówienie musi zostać nadane. Allegro go podaje, Erli nie, więc zamówienia z Erli nigdy nie są „po terminie”." },
    { term: "Import", text: "Pobranie zamówień (i innych danych) z Allegro lub Erli. Dzieje się automatycznie co kilkanaście minut albo na przycisk." },
    { term: "Tryb bezpieczny", text: "Dopóki jest włączony, Anvero nic nie wysyła do marketplace'ów i zapisuje tylko to, co by wysłał. Zalecany na początku i podczas prób." },
    { term: "Etykieta", text: "Dokument przesyłki. Allegro: „Wysyłam z Allegro” (kupowana w aplikacji, płatna); InPost: przesyłka do paczkomatu tworzona przez API." },
    { term: "Marża", text: "Sprzedaż minus opłaty marketplace'u minus koszt wytworzenia sprzedanych sztuk. Bez wpisanego kosztu jest to marża „przed kosztem”." },
    { term: "Raport bezrachunkowy", text: "Ewidencja sprzedaży do osób prywatnych zwolnionej z kasy rejestrującej (poz. 41) i raport dla księgowej." },
    { term: "Anonimizacja", text: "Usunięcie z zamówienia danych osobowych po upływie okresu przechowywania; zamówienie zostaje do statystyk, ale bez danych kupującego." },
  ],
};
